site_name: Subdue

pages:
 - Home: index.md
 - Getting Started:
     - Installation: installation.md
     - Python Native Mode: native.md
     - Network Mode: network.md
 - Supported Devices: supported_devices.md

theme: readthedocs