site_name: AMS Hardware Suite

pages:
 - Home: index.md
 - Getting Started:
     - Installation: installation.md
     - Python Native Mode: native.md
     - Standalone Mode: standalone.md
 - Supported Devices: supported_devices.md

theme: readthedocs